BEGIN TRANSACTION;
INSERT INTO `sub_categories` VALUES (1,'subcategory-one',2,'','');
INSERT INTO `sub_categories` VALUES (2,'subcategory-two',5,'','');
INSERT INTO `sub_categories` VALUES (3,'subcategory-three',3,'','');
INSERT INTO `sub_categories` VALUES (4,'subcategory-four',4,'','');
INSERT INTO `sub_categories` VALUES (5,'subcategory-five',1,'','');
INSERT INTO `schema_migrations` VALUES ('20161208181218');
INSERT INTO `schema_migrations` VALUES ('20161208193054');
INSERT INTO `schema_migrations` VALUES ('20161208195733');
INSERT INTO `companies` VALUES (1,'Company1',3,1,'Toronto','','');
INSERT INTO `companies` VALUES (2,'Company2',3,2,'Toronto','','');
INSERT INTO `companies` VALUES (3,'Company3',5,3,'Toronto','','');
INSERT INTO `companies` VALUES (4,'Company4',2,4,'Toronto','','');
INSERT INTO `companies` VALUES (5,'Company5',3,5,'Toronto','','');
INSERT INTO `categories` VALUES (1,'category-one','','');
INSERT INTO `categories` VALUES (2,'category-two','','');
INSERT INTO `categories` VALUES (3,'category-three','','');
INSERT INTO `categories` VALUES (4,'category-four','','');
INSERT INTO `categories` VALUES (5,'category-five','','');
INSERT INTO `ar_internal_metadata` VALUES ('environment','development','2016-12-08 20:00:28.591395','2016-12-08 20:00:28.591395');
COMMIT;
